# Welcome To The World Of Jupyter

<img style="float: left;"  src="images/city.png"  width="30%">

## 04-01. Jupyter Shortcuts And Basic Python

### Basic Practice

#### Learn the basic function you need to know.

#### 1. Basic Shortcut In Jupyter

In [0]:
#Use arrow button to move up and down

In [0]:
#Use Ctrl+Enter or Shift+Enter at this block to run it.

print("Hello Juypter")

Hello Juypter


In [0]:
#Use dd to delete this block.

print("Delete Me")

In [0]:
#Use B to create a new block Below.

#Then trying to wirte something in it. (like Print function.)

In [0]:
print("Hello")

Hello


#### 2. Basic Math Calculate & Print

In [0]:
#Remember to import these head file

import numpy  as  np
import scipy  as  sp
import cv2

from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = (10, 10)        # large images
plt.rcParams['image.interpolation'] = 'nearest'  # don't interpolate: show square pixels

In [0]:
#This is how variable work in Python.

a = 2

b = 3

c = a + b

print(c)

# Compile this block to see waht will happened.

#### 3. If Else

In [0]:
#This is how "if" work in Python. and print out "true".
#Below is code I use the variable last block to print out true.

if a == 2 :
    if c == 6 :             # <- If this line is true,         
        print("true")       # <- do this. 
    else :                  # <- Otherwise,
        print("false")      # <- do this. 

# Compile this block to see waht will happened.

NameError: name 'a' is not defined

#### 4. For Loop

In [0]:
#This is how "For" work in Python.
#Below is code how you can print the word "six" six time.

for i in range(2,4) :     # <- You can asign the range (a,b) by yourself, and it will run from a to b-1 
    for j in range(3):    # <- or just make it run from 0 to x-1                
        print ("six")

# Compile this block to see waht will happened.   

#### 5. Advance Print 

In [0]:
#This is how print can do in Python.
#(don't change line after you print, and print out variabe with other texts)

Apple = 5;
Banana = 10;
Cat = 10;

print("I have %d apple," %(Apple) ) ,
print("%d banana, and %d cat." %(Banana,Cat) )

# Compile this block to see waht will happened. 

I have 5 apple, 10 banana, and 10 cat.


#### 6. 2D Array

In [0]:
#This is how matrix work in Python.
#(don't change row after print a line, and print out variabe with other texts)

x = np.ones([3,3])
y = np.zeros([4,4])

print(x.shape)
print(x)
print("\n")
print(y.shape)
print(y)

# Compile this block to see waht will happened. 

(3, 3)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


(4, 4)
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


#### 7. Input

In [0]:
# This is how you can get input frome the keyboard.

temp = input("input:")

print(temp)

# Compile this block to see waht will happened. 

input:5
5


### Advance Chanllenge

#### Now with the knowledge above, trying to finish these task.

#### 1. Multiplication Table

In [0]:
#  Now, try to print a multiplication table (from 1~9) with for function

#  It should look like this 

#  1*1=1 1*2=2 ...
#  2*1=2 2*2=4 ...
#  ...

In [0]:
# Finish your code here #

#### 2. Matrix

In [0]:
#Now, try to create a 2d array with 1 on the border and 0 inside.

# It should look like this 

#        1  1  1  1
#        1  0  0  1
#        1  0  0  1
#        1  1  1  1


In [0]:
# Finish your code here #

#### 3.  Matrix With Input

In [0]:
#Now, try to combine "input", "array", "if", and "for"
#to create a 2d array with input (int) and output like this

# input 4
# 1 1 1 1
# 1 0 0 1
# 1 0 0 1
# 1 1 1 1

# input 7
# 1 1 1 1 1 1 1 
# 1 0 0 0 0 0 1
# 1 0 1 1 1 0 1
# 1 0 1 0 1 0 1
# 1 0 1 1 1 0 1
# 1 0 0 0 0 0 1
# 1 1 1 1 1 1 1

In [0]:
# Finish your code here #

####  4. Draw z = cos( x^2 + y^2 )

In [1]:
#Hint : We have done draw z = sin(x^2 + y^2)/(x^2 + y^2), just modify the code!

#Step:
    #1. import numpy & matplotlib.pyplot
    #2. meshgrid the x, y
    #3. use the result of meshgrid to draw